#!/bin/bash

SASE="DBSPERNS7"
DASE="DBSTERS7"
DATETIMEMARKER="20250120085227"
RUNPID="45893"

./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE BERS001  1 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERS000  1 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERS001  4 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERS004 16 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERSLOG  4 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERSPDM  1 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE CERSWRK  1 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE DERS002  8 $DATETIMEMARKER $RUNPID
./make_loadscript_by_SOURCEASE_DESTASE_DBNAME_NUMSTRIPS_DATEMARKER_ID.bash $SASE $DASE DERS003  4 $DATETIMEMARKER $RUNPID

exit 0
